---
services:
  audioteka-abs:
    image: ghcr.io/cznewt/audioteka-abs:main
    environment:
      - LANGUAGE=cz
      - ADD_AUDIOTEKA_LINK_TO_DESCRIPTION=false # Set to false to hide the Audioteka link in the description
    restart: unless-stopped
    ports:
      - "3001:3001"
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ./volume/audiobooks:/audiobooks
      - ./volume/podcasts:/podcasts
      - ./volume/metadata:/metadata
      - ./volume/config:/config
    restart: unless-stopped
